### ISSUE TITLE
pump channel control

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#33]
We are confused about fuel pump solenoid control

Which of start5 and/or start6 is controlling pump?
Does microcode match existing board?

Is pump controlled by both start5 and start6? if it's not, what is the other one controlling?

what pin do we expose on GDI4 connector with what kind of electrical considerations?

![image](https://user-images.githubusercontent.com/48498823/155337704-70b29eb8-53ad-436d-923d-99cba98e4b4d.png)

![image](https://user-images.githubusercontent.com/48498823/155337497-1a54322a-2dd5-4891-b0cb-8f5ac6440069.png)

**Comment by NOx-z** [comment]
per line 48 on the source on file,
https://github.com/rusefi/rusefi/blob/master/firmware/hw_layer/mc33816/rusefi/MicrocodeCh2/ch2.psc#L48
We use START6, and we turn on High-Side5 (VBat), and Low-Side6 drivers with it.

At a glance the board appears accurate. There is no populated LowSide5.

We made the decision to only map one (excluding START5), and left the other unmapped + unpopulated because the only way we could use the other was to then switch off whatever START6 was targeting, they both can not be on at the same time. We examined general use cases and found we did not have another solenoid to power intermittently.

I am unaware at the moment where the pins for GDI4 are defined. All of the START signal should be similar, that is, they are enabled at a high level (VccIO) of the MC33816/PT2001. They are not driving anything themselves beyond a signal.

**Comment by rusefillc** [comment]
@Qwerty-OFF let's do both "same as injectors" via external pin and a jumpers allowing to switch to internal pump channel control from stm32f103

**Comment by rusefillc** [comment]
What jumper controls internal/external pump control?

please add explicit comment right on schematics

**Comment by Qwerty-OFF** [comment]
No you can use wire frome any stm32 pad:
![image](https://user-images.githubusercontent.com/4116383/159343042-67f79db5-4b19-423f-8926-5342cb85fe1c.png)
to connector jumpers:
![image](https://user-images.githubusercontent.com/4116383/159343085-e1e3c6d2-05f0-4f7a-95d2-eaaf68620305.png)
Do we need special jumper for this?

**Comment by rusefillc** [comment]
Yes lets add a 0R

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/159349919-784e73c5-34b6-4bcd-a0da-e8f2d4bf5726.png)
